# Build settings
markdown: kramdown
includes_dir: _sections

sass:
    style: compressed
    
gems: 
    - jekyll-feed
    - jekyll-sitemap
exclude:
    - Gemfile
    - Gemfile.lock
    - docker-compose.yml
